import Header from './components/Header'
import './globals.css'

export const metadata = {
  title: 'Netflix Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className='bg-black text-white scrollbar-hide'>
        <Header />
        {children}
      </body>
    </html>
  )
}
