import Header from '../components/Header'
import SessionProvider from '../components/SessionProvider'
import './globals.css'

export const metadata = {
  title: 'Netflix Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en" >
      <link rel="icon" href="/Logo.png" />
      <body className='bg-black text-white scrollbar-hide'>
        <Header />
        {children}
      </body>
    </html>
  )
}
